Sprint 10 - v1.0
undpun/java-filmorate pull request #4
Opened 2023-03-14 16:20 UTC by undpun

2023-03-15 19:04 UTC, ohelly requested changes
Привет! Превосходная работа, все работает корректно. Я оставил несколько рекомендаций, на которые стоит обратить внимание. Исправлять их необязательно, в таком случае можешь просто прислать текущий вариант снова и я приму работу.

2023-03-15 19:04 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
Почему удалена валидция из этого класса и из класса FIlm? А также аннотация ``@Valid`` из контроллеров. Понимаю, что теперь проверяется через класс Validator, но почему?)

2023-03-15 21:35 UTC, undpun commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
Причина в поле name класса User - я хотел чтобы параметр User метода контроллера и валидировал тело запроса и при этом проверял и выставлял по надобности поле name. Создание отдельного метода для этого показалось костылем. Да и классы-модели (User, Film) воспринимались какими-то сложными для чтения визуально. И мне сказали что создание отдельного класса для валидации является распростаненной практикой.
Я был бы рад использовать только аннотации, но найти не смог (а в создании своей запутался). Как лучше сделать: оставить как есть или есть решение что я пропустил?

2023-03-15 22:15 UTC, undpun commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage) {
интерфейс UserStorage может иметь множество имплементаций. как спринг или ломбок поймут какой бин встраивать?

2023-03-18 10:46 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage userStorage) {
Можно использовать аннотацию ``@Qualifier``, это даст понять спрингу, какой именно инжектить. А для того, чтобы ломбок добавил эту аннотацию необходио добавить для него параметр, https://stackoverflow.com/questions/38549657/is-it-possible-to-add-qualifiers-in-requiredargsconstructoronconstructor

2023-03-18 10:52 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .limit(Math.min(count, films.size()))
Рекомендация: Math.min также необязательно использовать. Stream поймет, если размер листа меньше чем count, то вернет столько, сколько есть.

2023-03-18 10:52 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
Какого-то единого решения нет, обычно используют аннотации + ручную проверку для некоторых случаев(как например для поля name класса User). Но и тот и другой вариант вполне хорош. Если понимаешь, что тяжело читаются классы из-за аннотаций, то вполне нормально использовать только ручные проверки.

2023-03-18 10:55 UTC, ohelly approved these changes
Привет! Все супер, работу принимаю. Удачи в дальнейшем обучении!

2023-03-18 10:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user == null)
Рекомендация: Чтобы избавиться от проверок на null можно пользователя достать не напрямую из стораджа, а использовать метод get данного сервиса. Аналогично и в FilmService.

2023-03-22 15:03 UTC, merged