Sprint 11 - SQL
undpun/java-filmorate pull request #5
Opened 2023-04-14 23:13 UTC by undpun

2023-04-16 10:54 UTC, ohelly requested changes
Привет! Видно, что проделана большая работа, В целом отличное приложение. Есть несколько замечаний, которые необходимо исправить. В основном они связаны с тем, что делается несколько запросов вместо одного. Старайся делать так, чтобы приходилось меньше нагружать БД. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае возникновения вопросов можешь обращаться ко мне в пачку.

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate, UserDbStorage userStorage, GenreDbStorage genreStorage, MpaDbStorage mpaStorage) {
Рекомендация: Чтобы не писать конструктор каждый раз в ручную можно использовать аннотацию ломбока ``@RequiredArgsConstructor``, которая создает автоматически конструктор для всех final полей. К тому же, необходимо чтобы конструктор был зависим от интерфейсов, а не от классов реализаций(относится к UserDbStorage). Чтобы инжектился нужный нам бин, в случае когда классов реализующих интерфейс несколько, необходимо использовать аннотацию ``@Qualifier``.
![image](https://user-images.githubusercontent.com/51891976/232297676-2192344b-1878-4798-b083-a40371dc47d4.png)
К тому же, чтобы ломбок мог копировать аннотации необходимо добавить следующую строку в lombok.config:
![image](https://user-images.githubusercontent.com/51891976/232297817-70952fdf-bc60-409c-9747-1a100d20ad1b.png)

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.getLikes().forEach(userId -> jdbcTemplate.update("INSERT INTO film_like(film_id, user_id) " +
Рекомендация: Для лайков в данном случае сделать batchUpdate, тогда вставка произойдет за один запрос, вместо нескольких отдельных инсертов, как сейчас.

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +                .forEach(genre -> jdbcTemplate.update(addFilmGenreRelationSQLQuery, film.getId(), genre.getId()));
Необходимо исправить: Необходимо сделать, чтобы все жанры вставлялись одним запросом, можно использовать batchUpdate.

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Film film = new Film();
Рекомендация: Маппинг полей в новый объект лучше вынести в отдельный метод, так как он повторяется здесь и в методе getAll

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.getLikes().forEach(userId -> jdbcTemplate.update("INSERT INTO film_like(film_id, user_id) " +
Рекомендацияя: В данном случае лучше тоже сделать через batchUpdate

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setMpa(mpaStorage.get(filmRows.getInt("mpa_id")));
Необходимо исправить: MPA рейтинг можно доставать сразу с помощью оператора join в запросе:
![image](https://user-images.githubusercontent.com/51891976/232300280-4525478c-ddea-41e5-ae1e-66de48046972.png)
Аналогично и для метода getAll

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.setGenres(genreStorage.getFilmGenres(film.getId()));
Необходимо исправить: Необходимо получать жанры за один запрос в базу, вне зависимости от того, для скольких фильмов. Сейчас получается, что на N фильмов делается N запрос для получения жанров. Такой подход довольно ресурсозатратен, необходимо всегда стараться уменьшать количество запрос в БД. Для этого тебе поможет запрос с оператаром IN(чтобы получить жанры), а также структура данных Map.
![image](https://user-images.githubusercontent.com/51891976/232300817-a533d8ba-0327-48fe-a5d0-7f92c52e5e54.png)

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public UserDbStorage(JdbcTemplate jdbcTemplate, FriendDbStorage friendStorage) {
Рекомендация: Аналогичная рекомендация по поводу аннотации ``@RequiredArgsConstructor``

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendDbStorage.java
> +            friends.forEach(friendId -> jdbcTemplate.update(addUserFriendRelationSQLQuery, user.getId(), friendId));
Рекомендация: Также лучше использовать batchUpdate

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserDbStorage userStorage) {
Необходимо, чтобы конструктор зависел от интерфейсов, а не от классов реализаций. Используй аннотацию ``@Qualifier``

2023-04-16 10:54 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final UserStorage userStorage;
Необходимо исправить: Необходимо UserStorage заменить на UserService, так как обычно, сервис обращается напрмямую только к "своему" хранилищу, доступ к другим осуществляется через сервисы.

2023-04-16 15:37 UTC, undpun commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate, UserDbStorage userStorage, GenreDbStorage genreStorage, MpaDbStorage mpaStorage) {
Intellij ругается когда использую Qualifier:
- Lombok does not copy the annotation 'org.springframework.beans.factory.annotation.Qualifier' into the constructor
И еще ошибка при запуске выходит что не может определить какой bean инжектить. В группе сказали что проблема в том что это поддерживается в последней версии lombok которая в свою очередь совместима со спрингом от 3 версии.
Поэтому решил оставить все как есть. Слишком запара менять версии у спринга и ломбока

2023-04-17 19:02 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate, UserDbStorage userStorage, GenreDbStorage genreStorage, MpaDbStorage mpaStorage) {
Привет! Да, идея ругается, точнее предупреждает, о том, что ломбок не умеет копировать аннотации в свои автогенерируемые конструкторы. Эту проблему решает строчка в файле lombok.config(мой 2 скрин), с этим параметром ломбок может копировать аннотации в свои конструкторы. То что выше на моих скринах - работает и запускается, это я делал на твоем проекте.
Также обрати внимание, если будет дописывать строчку в lombok.config идея тебе может автодополнить строку, которую ты пишешь. Так вот, идея в данном случае дополняет не верно, она пишет ``lombok.copybaleannotations``(не верный вариант) вместо ``lombok.copybaleAnnotations``

2023-04-17 19:51 UTC, undpun commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate, UserDbStorage userStorage, GenreDbStorage genreStorage, MpaDbStorage mpaStorage) {
я пробовал. видимо чем-то у нас отличаются настройки

<img width="500" alt="Screenshot 2023-04-18 at 01 16 49" src="https://user-images.githubusercontent.com/72478351/232594536-b6e3b4a6-6c34-4843-8d0a-55eff0dd79a5.png">

<img width="697" alt="Screenshot 2023-04-18 at 01 15 30" src="https://user-images.githubusercontent.com/72478351/232594861-7dae1eb5-2f98-4f93-ba3e-1c3de71e24b8.png">

<img width="1017" alt="Screenshot 2023-04-18 at 01 50 30" src="https://user-images.githubusercontent.com/72478351/232595267-cd6e8e53-0a20-4567-8b25-c09960c185de.png">

2023-04-17 19:55 UTC, ohelly requested changes
Привет! Осталось несколько замечаний, которые необходимо исправить. Также у тебя не проходит пайплайн, по этому поводу необходимо обратиться к наставнику.

2023-04-17 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate, UserDbStorage userStorage, GenreDbStorage genreStorage, MpaDbStorage mpaStorage) {
Рекомендация: Если так и не получается воспользоваться ломбоком, то можно прям в конструкторе дописать аннотацию ``@Qualifier``, чтобы он не зависел от классов реализаций, а зависел от интерфейсов.
![image](https://user-images.githubusercontent.com/51891976/232586290-06449792-8cc6-40fa-abee-bb644d27e943.png)

2023-04-17 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +                .forEach(genre -> jdbcTemplate.batchUpdate(
Необходимо исправить: Неправильно использован batchUpdate, в данном случае также выполняется несколько запросов для вставки жанров(в цикле для каждого жанра делается запрос в БД).
![image](https://user-images.githubusercontent.com/51891976/232589178-b7630941-2d2c-43f9-8f07-1950f58e4890.png)

2023-04-17 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.getLikes().forEach(userId -> jdbcTemplate.batchUpdate(String.format("INSERT INTO film_like(film_id, user_id) " +
Рекомендация: batchUpdate работает немного по другому. Описал как именно в GenreDbStorage. Также для жанров это обязательно к исправлению, для всего другого - рекомендация.

2023-04-17 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.getLikes().forEach(userId -> jdbcTemplate.batchUpdate(
Рекомендация: Аналогичная рекомендация про batchUpdate

2023-04-17 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Map<Integer, Set<Genre>> filmGenresMap = genreStorage.getFilmsGenresMap();
Рекомендация: Сейчас достаются из БД все жанры и только потом в коде достаются необходимые. Можно доставать сразу необходимые жанры из БД с помощью запроса с оператором IN:
![image](https://user-images.githubusercontent.com/51891976/232592325-6ef8dac2-f84b-4100-ba68-ac36544a23e7.png)
![image](https://user-images.githubusercontent.com/51891976/232592733-d462df1a-c15e-48d5-be63-bc190bd1c8c7.png)

2023-04-17 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserDbStorage userStorage) {
Необходимо исправить: Конструктор должен зависеть от интерфейсов, а не от классов реализаций.

2023-04-17 19:55 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmDbStorage filmStorage, UserDbStorage userStorage) {
Необходимо исправить: Не исправлено предыдущее замечание, о том, что класс сервис обращается к другим хранилищам через их сервисы, а не напрямую.

2023-04-17 21:50 UTC, ohelly approved these changes
Все отлично, исправлены все замечания. Работу принимаю, удачи в дальнейшем обучении!

2023-04-17 22:04 UTC, merged